apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gateway
  namespace: fairwear
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`fairwear.leedrisdev.com`)
    services:
    - kind: Service
      name: gateway
      namespace: fairwear
      port: 80
  # tls:
  #   certResolver: production