apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodonyou-scrapper # Name of the deployment
  namespace: fairwear # Name of the namespace
  labels:
    app: goodonyou-scrapper # Name of your application
spec:
  selector:
    matchLabels:
      app: goodonyou-scrapper # Name of your application
  replicas: 2 # Number of replicas
  template:
    metadata:
      labels:
        app: goodonyou-scrapper # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: goodonyou-scrapper # Name of the container
        image: docker-registry.leedrisdev.engineer/goodonyou_scrapper_api:develop-101 # The image you want to run
        ports:
        # Ports are the ports that your application uses.
        - containerPort: 80 # The port that your application uses
      imagePullSecrets: # If you need to pull from a private registry
      - name: regcred # Name of the secret