apiVersion: v1
kind: Service
metadata:
  name:  goodonyou-scrapper
  namespace: fairwear
spec:
  selector:
    app:  goodonyou-scrapper
  type:  ClusterIP
  # ClusterIP means this service can be accessed by any pod in the cluster
  ports:
  - name:  http
    port:  80
    targetPort: 80