apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-and-product-api # Name of the deployment
  namespace: fairwear # Name of the namespace
  labels:
    app: brand-and-product-api # Name of your application
spec:
  selector:
    matchLabels:
      app: brand-and-product-api # Name of your application
  replicas: 5 # Number of replicas
  template:
    metadata:
      labels:
        app: brand-and-product-api # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: brand-and-product-api # Name of the container
        image: docker-registry.leedrisdev.engineer/brand_and_product_api:develop-62 # The image you want to run
        imagePullPolicy: Always # Always pull the image
        ports:
        # Ports are the ports that your application uses.
        - containerPort: 80 # The port that your application uses
      imagePullSecrets: # If you need to pull from a private registry
      - name: regcred # Name of the secret