apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-data-retriever # Name of the deployment
  namespace: fairwear # Name of the namespace
  labels:
    app: product-data-retriever # Name of your application
spec:
  selector:
    matchLabels:
      app: product-data-retriever # Name of your application
  replicas: 2 # Number of replicas
  template:
    metadata:
      labels:
        app: product-data-retriever # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: product-data-retriever # Name of the container
        image: docker-registry.leedrisdev.engineer/data_retriever_api:develop-44 # The image you want to run
        imagePullPolicy: Always # Always pull the image
        ports:
        # Ports are the ports that your application uses.
        - containerPort: 80 # The port that your application uses
      imagePullSecrets: # If you need to pull from a private registry
      - name: regcred # Name of the secret