apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-and-product-db # Name of the deployment
  namespace: fairwear # Name of the namespace
  labels:
    app: brand-and-product-db # Name of your application
spec:
  selector:
    matchLabels:
      app: brand-and-product-db # Name of your application
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: brand-and-product-db # Name of your application
    spec:
      containers:
      # Containers are the individual pieces of your application that you want
      # to run.
      - name: brand-and-product-db # Name of the container
        image: docker-registry.leedrisdev.engineer/brand_and_product_database:macos # The image you want to run
        env:
        # Environment variables are the variables that your application uses.
        - name: POSTGRES_USER # Name of the environment variable
          value: "fairwear" # Value of the environment variable
        - name: POSTGRES_PASSWORD # Name of the environment variable
          value: "fairwear" # Value of the environment variable
        - name: POSTGRES_DB # Name of the environment variable
          value: "fairwear_brand_and_product_database" # Value of the environment variable
        ports:
        # Ports are the ports that your application uses.
        - containerPort: 5432 # The port that your application uses
      imagePullSecrets: # If you need to pull from a private registry
      - name: regcred # Name of the secret